# Generated by roxytest: Do not edit by hand!

# File R/tree.R: @tests

test_that("Function node_label() @ L19", {
  expect_equal(node_label(tidyged::sample555, "@I1@"),
  "I1(\"<b>Robert Eugene Williams</b><br>b. 2 Oct 1822<br>Weston, Madison, Connecticut, United States of America<br>d. 14 Apr 1905<br>Stamford, Fairfield, Connecticut, United States of America\")")
  expect_equal(node_label(tidyged::sample555, "@I3@"),
  "I3(\"<b>Joe Williams</b><br>b. 11 Jun 1861<br>Idaho Falls, Bonneville, Idaho, United States of America<br> - Still living\")")
  expect_equal(node_label(tidyged::sample555, "@F1@"),
  "F1(\"m. Dec 1859<br>Rapid City, Pennington, South Dakota, United States of America\")")
})


test_that("Function node_style() @ L78", {
  expect_equal(node_style(tidyged::sample555, "@F1@"),
  "style F1 fill:lightgrey, stroke:black")
  expect_equal(node_style(tidyged::sample555, "@I1@"),
  "style I1 fill:lightblue, stroke:black")
})

